// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dyrhsseymnlqjyhwjgag.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR5cmhzc2V5bW5scWp5aHdqZ2FnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1ODk3NDQsImV4cCI6MjA1OTE2NTc0NH0.uaTdmKfMw8gWk25fA85oFWQzXkHCf7d0c0DXpNxx4V8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);